---
- name: Upgrade apt packages
  apt: upgrade=yes
       update_cache=yes

- name: Install Rainy prerequisites
  apt: pkg={{ item }}
  with_items:
    - libsqlite3-0
    - mono-complete
    - unzip

- name: Add the rainy user
  user: name=rainy
        home=/home/rainy
        shell=/bin/bash
        comment="Rainy User"

- name: Download Rainy
  get_url: url={{ rainy_download_location }}
           dest=/home/rainy/{{ rainy_archive_filename }}
           sha256sum={{ rainy_checksum }}

- name: Extract the Rainy archive
  command: unzip {{ rainy_archive_filename }}
           creates={{ rainy_location }}/Rainy.exe
           chdir=/home/rainy
  sudo: yes
  sudo_user: rainy

- name: Set permissions on the Rainy directory
  file: path={{ rainy_location }}
        owner=rainy
        group=rainy
        mode=750
        state=directory

- name: Generate Rainy configuration file
  template: src=settings.conf.j2
            dest={{ rainy_location }}/settings.conf
            owner=rainy
            group=rainy
            mode=640
